# permissions for end users to view atobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: atob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atob-controller
    app.kubernetes.io/part-of: atob-controller
    app.kubernetes.io/managed-by: kustomize
  name: atob-viewer-role
rules:
- apiGroups:
  - atob.itihey.com
  resources:
  - atobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - atob.itihey.com
  resources:
  - atobs/status
  verbs:
  - get
