---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - atob.itihey.com
  resources:
  - atobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atob.itihey.com
  resources:
  - atobs/finalizers
  verbs:
  - update
- apiGroups:
  - atob.itihey.com
  resources:
  - atobs/status
  verbs:
  - get
  - patch
  - update
