apiVersion: atob.itihey.com/v1
kind: Atob
metadata:
  name: atob-sample
spec:
  git:
    url: https://github.com/itihey/tikuAdapter.git
    branch: main
  image:
    name: test/tiku
    tag: latest
    registry: docker.io

